#!/usr/bin/env sh

set -euf -o pipefail

KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-"localhost:9092"}

docker run --rm -t --network host --volume "./examples:/cwd" \
  -e KAFKA_BOOTSTRAP_SERVERS="$KAFKA_BOOTSTRAP_SERVERS" \
  pyrandall:latest \
  --config /cwd/config/test_env.json $@
